---
# Run this playbook using : `ansible-playbook -i hosts benchmark.yml -vvvv` from inside the ansible directory in repo
- name: Fetch and install packages/tools to run Docker 
  hosts: all
  gather_facts: False
  
  pre_tasks:
  # Install python - required to run Ansible commands on host machine
  - name: Install python 2
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

  - name: Install pip
    become: true
    apt: 
        name: python-pip
        update_cache: yes 
        cache_valid_time: 600

  # install pycurl - required for installing docker on host machine
  - name: install pycurl
    become: true
    apt: 
        name: python-pycurl 
        update_cache: yes 
        cache_valid_time: 600

  # install docker
  - name: Update the apt package index
    become: true
    apt:
        update_cache: yes

  - name:  Install packages to allow apt to use a repository over HTTPS
    become: true
    apt: 
        name: "{{item}}"
    with_items:
          - apt-transport-https=1.2.24
          - apt-transport-https=1.2.24
          - curl=7.47.0-1ubuntu2.2
          - software-properties-common=0.96.20.7

  - name: Add Docker’s official GPG key
    become: true
    raw: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

  - name: Retrieve the ubuntu distribution
    command: lsb_release -cs
    register: lsbrelease

  - name: Retrieve machine architecture
    command: dpkg --print-architecture
    register: arch

  - name: Set up the stable repository for docker
    become: true
    apt_repository:
      repo: deb [arch={{arch.stdout}}] https://download.docker.com/linux/ubuntu {{lsbrelease.stdout}} stable

  - name: Install Docker
    become: true
    apt: 
        name: docker-ce
        update_cache: yes 
        cache_valid_time: 600

  - name: Install docker-py
    become: true
    pip:
        name: docker-py
  
  tasks:
  # Clone github repo, pull image from docker, create wiki corpus, run benchmark in docker and finally mail the report
  - name: Clone benchamrk repo
    git:
      repo: https://github.com/manneshiva/benchmark-word2vec-frameworks.git
      dest: /home/ubuntu/benchmark-word2vec-frameworks/
      clone: yes
      recursive: yes

  - name: Pull docker image from Docker Hub
    become: true
    docker_image:
      name: manneshiva/playground:benchmarkword2vec-cpu

  - name: Download wiki dump
    get_url:
      url: https://dumps.wikimedia.org/enwiki/20170801/enwiki-20170801-pages-articles-multistream.xml.bz2
      dest: /home/ubuntu/benchmark-word2vec-frameworks/data/

  - name: Process wiki dump to create corpus
    become: true
    command: >
      python wiki2corpus.py --wikifile ./data/enwiki-20170801-pages-articles-multistream.xml.bz2 
      --corpusfile ./data/enwiki.cor --words_per_line 1000 arg1
    args:
      chdir: /home/ubuntu/benchmark-word2vec-frameworks/

  - name: Run benchamrk inside Docker
    become: true
    command: >
      sudo docker run --rm -w /benchmark-word2vec-frameworks/ 
      -v /home/ubuntu/benchmark-word2vec-frameworks:/benchmark-word2vec-frameworks/ 
      manneshiva/playground:benchmarkword2vec-cpu 
      python benchmark.py --platform aws --frameworks gensim originalc tensorflow dl4j --file data/enwiki.cor --epochs 4 --batch_size 16 --workers 7 --size 100

  # Mailing benchmark report using yahoomail SMTP servers
  - name: Install sendemail
    become: true
    apt:
        name: sendemail
        update_cache: yes 
        cache_valid_time: 600

  # install libnet-ssleay-perl & libio-socket-ssl-perl for TLS support
  - name: Install libnet-ssleay-perl
    become: true
    apt:
        name: libnet-ssleay-perl
        update_cache: yes 
        cache_valid_time: 600
  - name: Install libio-socket-ssl-perl
    become: true
    apt:
        name: libio-socket-ssl-perl
        update_cache: yes 
        cache_valid_time: 600

  # email the benchmark report
  - name: Mail Benchamrk Report
    command: >
      sendemail -f "shiva.manne@yahoo.com" -t "shiva.manne@yahoo.com" -u "Word2Vec Benchmark Report - {{inventory_hostname}}" 
      -m "Benchmark report attached within this mail." -xu "shiva.manne@yahoo.com" -xp "Benchmark@gensim" -o tls=yes 
      -s "smtp.mail.yahoo.com:587" -a ./aws-report.json
    args:
      chdir: /home/ubuntu/benchmark-word2vec-frameworks/
