---
# Run this playbook using : `ansible-playbook -i hosts benchmark.yml -v` from inside the ansible directory in repo
- name: Fetch and install packages/tools to run Docker 
  hosts: all
  gather_facts: False
  
  pre_tasks:
  # Install python - required to run Ansible commands on host machine
  - name: Install python 2
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

  - name: Install pip
    become: true
    apt: 
        name: python-pip
        update_cache: yes 
        cache_valid_time: 600

  # install pycurl - required for installing docker on host machine
  - name: install pycurl
    become: true
    apt: 
        name: python-pycurl 
        update_cache: yes 
        cache_valid_time: 600

  # install docker
  - name: Update the apt package index
    become: true
    apt:
        update_cache: yes

  - name:  Install packages to allow apt to use a repository over HTTPS
    become: true
    apt: 
        name: "{{item}}"
    with_items:
          - apt-transport-https=1.2.24
          - apt-transport-https=1.2.24
          - curl=7.47.0-1ubuntu2.3
          - software-properties-common=0.96.20.7

  - name: Add Docker’s official GPG key
    become: true
    raw: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

  - name: Retrieve the ubuntu distribution
    command: lsb_release -cs
    register: lsbrelease

  - name: Retrieve machine architecture
    command: dpkg --print-architecture
    register: arch

  - name: Set up the stable repository for docker
    become: true
    apt_repository:
      repo: deb [arch={{arch.stdout}}] https://download.docker.com/linux/ubuntu {{lsbrelease.stdout}} stable

  - name: Install Docker
    become: true
    apt: 
        name: docker-ce
        update_cache: yes 
        cache_valid_time: 600

  - name: Install docker-py
    become: true
    pip:
        name: docker-py

  - name:  Install packages - htop, tmux, less, vim
    become: true
    apt: 
        name: "{{item}}"
    with_items:
          - htop
          - tmux
          - less
          - vim
  
  tasks:
  # Clone github repo, pull image from docker, create wiki corpus, run benchmark in docker and finally mail the report
  - name: Clone benchamrk repo
    git:
      repo: https://github.com/manneshiva/benchmark-word2vec-frameworks.git
      dest: /home/ubuntu/benchmark-word2vec-frameworks/
      clone: yes
      recursive: yes

  - name: Pull docker image from Docker Hub
    become: true
    docker_image:
      name: manneshiva/playground:benchmarkword2vec-cpu-tfsource

  - name: Make persistent directory - for docker
    become: true
    file: path=/persistent/ state=directory

  - name: Download wiki dump part 1
    become: true
    get_url:
      url: https://github.com/manneshiva/benchmark-word2vec-frameworks/releases/download/v0.1.0/enwiki-20170501-2M-1.cor.bz2
      dest: /persistent/

  - name: Download wiki dump part 2
    become: true
    get_url:
      url: https://github.com/manneshiva/benchmark-word2vec-frameworks/releases/download/v0.1.0/enwiki-20170501-2M-2.cor.bz2
      dest: /persistent/

  - name: Unzip wiki files
    become: true
    command: >
      bunzip2 enwiki-20170501-2M-1.cor.bz2 && 
      bunzip2 enwiki-20170501-2M-2.cor.bz2 arg1
    args:
      chdir: /persistent/

  - name: Combine wiki files
    become: true
    shell: cat enwiki-20170501-2M-1.cor enwiki-20170501-2M-2.cor > enwiki-20170501-2M.cor
    args:
      chdir: /persistent/

  # # Mailing benchmark report using yahoomail SMTP servers
  # - name: Install sendemail
  #   become: true
  #   apt:
  #       name: sendemail
  #       update_cache: yes 
  #       cache_valid_time: 600

  # # install libnet-ssleay-perl & libio-socket-ssl-perl for TLS support
  # - name: Install libnet-ssleay-perl
  #   become: true
  #   apt:
  #       name: libnet-ssleay-perl
  #       update_cache: yes 
  #       cache_valid_time: 600
  # - name: Install libio-socket-ssl-perl
  #   become: true
  #   apt:
  #       name: libio-socket-ssl-perl
  #       update_cache: yes 
  #       cache_valid_time: 600

  # # email the benchmark report
  # - name: Mail Benchamrk Report
  #   command: >
  #     sendemail -f "shiva.manne@yahoo.com" -t "shiva.manne@yahoo.com" -u "Word2Vec Benchmark Report - {{inventory_hostname}}" 
  #     -m "Benchmark report attached within this mail." -xu "shiva.manne@yahoo.com" -xp "Benchmark@gensim" -o tls=yes 
  #     -s "smtp.mail.yahoo.com:587" -a ./*-report.json
  #   args:
  #     chdir: /benchmark-word2vec-frameworks/persistent/
